name: jitsi
description: "A Jitsi Meet App."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  jitsi_meet_flutter_sdk: ^11.1.1
  flutter_callkit_incoming: ^2.5.2
  firebase_core:
  huawei_hmsavailability:
  firebase_messaging:
  googleapis_auth:
  huawei_push:
  cloud_firestore:
  firebase_auth:
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/

